### ISSUE TITLE
哈喽，安装不成功。。。。是否需要倒入SQL呢？

### ISSUE THREAD

**Issue by SeonMe** [eyblog/blog#2]

**Comment by lscho** [comment]
对的，需要导入数据库，然后修改数据库配置。

**Comment by SeonMe** [comment]
gulp编译是在哪个目录执行呢？我找不到配置文件。。。。。

**Comment by lscho** [comment]
gulp的配置文件没有上传，因为其中有一部分插件是修改过的，直接运行的话报错。。如果你需要开发环境的话进78078316这个qq群。我把整个node_modules都给你一份

**Comment by SeonMe** [comment]
好的。已经加了
